# Generated by Django 3.2 on 2021-04-12 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Padlets',
            fields=[
                ('p_content', models.CharField(max_length=1000)),
                ('p_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
