# Generated by Django 3.2 on 2021-04-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Padlets',
            new_name='Padlet',
        ),
    ]
