# Generated by Django 3.2 on 2021-04-13 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlet', '0002_rename_padlets_padlet'),
    ]

    operations = [
        migrations.AddField(
            model_name='padlet',
            name='allowed_users',
            field=models.CharField(default='[]', max_length=500),
        ),
    ]
