# Generated by Django 3.2 on 2021-04-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlet', '0003_padlet_allowed_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=1000)),
                ('padlet_admin', models.CharField(max_length=1000)),
                ('padlet_participant', models.CharField(max_length=1000)),
            ],
        ),
    ]
