# Generated by Django 3.2 on 2021-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlet', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_owner',
            field=models.CharField(default='', max_length=100, primary_key=True, serialize=False),
        ),
    ]
